# version: 2.1
# orbs:
#   cypress: cypress-io/cypress@2
# workflows:
#   build:
#     jobs:
#       # "cypress" is the name of the imported orb
#       # "run" is the name of the job defined in Cypress orb
#       - cypress/run:
#           start: npm start
#           wait-on: 'http://localhost:3000'

version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:16.13.2
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build React App
          command: npm run build
      - save_cache:
          key: app-build-cache-{{ .Branch }}
          paths:
            - ./build
      - run:
          name: Deploy to Netlify
          command: ./node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir=build
orbs:
  cypress: cypress-io/cypress@2
workflows:
  version: 2
    build:
    jobs:
      # "cypress" is the name of the imported orb
      # "run" is the name of the job defined in Cypress orb
      - cypress/run:
          start: npm start
          wait-on: 'http://localhost:3000'
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
